sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kr6NSh6Zfr8VGTj0R6zwxdyCQZ7lLONE91onLd/W6vsM3UoqpSpvfkY6VBmlXkyi5UyPMc3HHaN2r9eowJHJ00ub1VXV7M2r/g8vPU5vBhhVhPJG1L9NzQWWEDn077gCusR3sKHEUsgtzlQkd17H47++lSh97bhbtStlUEpYcdhaAfYknd94hqqjBBT8E7CxVdqCOkB6EWDuJAtRe+wk6qsDSBTfDBpnmdRDebTEtuTTE9LZVDQGVS4kXa6R2gTGHYxbgeHseRDYUUKQzcvqcxPpUxoX/yrlTpDTNTMy66BrMK5ynKGmdoc7YsRupxlART421S0WYvayPlAz34ILmtZdLElyiGVgymroLOdhfNNp81+csRcT2hAg8I50el4/niFH/FWtiqcxIl6mQyuzaZWY3aMFPZ3sHTEJszAlfS4tC2x17xFVdGEln5Fulp+5yat4MZOR5wh9lly/o34T5hqbPC0ox/JF+64qB9AQRV5y0zt/MGPk+Qm5maEHr+wphV+S4CuDe0EpoVs+4lFhjRVqo5e2FYbUf2wu6bLOUjdaKBYss3bTTMD6/T5E+jIHfu19yKmDjDD25UtNNK1ivH8t936T8JU0+NxDXkrzmH9dVZqA4Uc4M640RrHE4pnONdyVoBIIlqRvS9NLYaWyLJgOOBdVIAUNVPoCrR+vD0A=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Diary-of-a-Goose-Girl_1867
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy